config/routes.rb
Rails.application.routes.draw do
  get 'todos', to: 'todos#index'
  get 'todos/list', to: 'todos#list', as: 'list_todo'
  get 'todos/new', as: 'new_todo'
  post 'todos', to: 'todos#create'
  get 'todos/:id', to: 'todos#show', as: 'show_todos'
  get 'todos/:id/edit', to: 'todos#edit', as: 'edit_todo'
  patch 'todos/:id', to: 'todos#update', as: 'todo'
  delete 'todos/:id', to: 'todos#destroy', as: 'delete_todo'
  get 'todos/:id/complete', to: 'todos#complete', as: 'complete_todo'
  put 'todos/:id', to: 'todos#complete_update'
  root 'todos#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todo.rb
class Todo < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
    before_action :set_todo, only: [:edit, :show, :update, :destroy, :complete]
    
    def index
    @todos = Todo.all
    end

    def new
        @todo = Todo.new
    end

    def create 
        @todo = Todo.new(todo_params)
        if @todo.save
            redirect_to todos_path
        else
            render :new
                
        end
    end

    def show 
    end

    def edit 
    end

    def update
        @todo.update(todo_params)
        redirect_to todos_path
    end

    def destroy
        @todo.destroy
        redirect_to todos_path
    end

    def complete 
        @todo.update_attributes(completed: true)
        redirect_to todos_path
    end

    def list
        @todo_completed = Todo.where(completed: true)   #trae todos los datos del modelo (recurso) Entries
        @todo_uncompleted = Todo.where(completed: false)
    end


    private
    def todo_params 
    params.require(:todo).permit(:completed, :description)
    end
    def set_todo
        @todo = Todo.find(params[:id])
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TodoApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render 'todos/navbar'%>
  <br>
  <br>
  <br>

    <%= yield %>
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
</html>

app/views/todos/_form.html.erb
<div class='row'>
    <div class="col-md-6 offset-md-3">
        <%= form_with(model: @todo, local: true) do |f| %>
            <div class="form-check">
                <%= f.check_box :completed, class: 'form-check-input' %>
                <%= f.label :completed, class: 'form-check-label', for: 'completed' %>
            </div>
            <div class="form-group">
                <%= f.label :description %>
                <%= f.text_field :description, class: 'form-control' %>
            </div>
            <br>
            
            <%= f.submit class: 'btn btn-info'%>
        <% end %>
    </div>
</div>

app/views/todos/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
<%= link_to "Index", root_path, class: 'navbar-brand' %> 
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
       <%= link_to "List", list_todo_path, class: 'nav-link'%>
      </li>
      <li class="nav-item">
        <%= link_to  "New", new_todo_path, class: 'nav-link' %>
      </li>
    </ul>
  </div>
</nav>

app/views/todos/edit.html.erb
<%= render 'form', todo: @todo %>

app/views/todos/index.html.erb
<% @todos.each_slice(1) do |one_todo| %>
<div class="card-deck">
<% one_todo.each do |todo| %>

  <div class="card">
    <div class="card-body">
      <div class="form-check">
        <%= check_box_tag(:completed, todo.completed, todo.completed, disabled: true) %>
        <% label :completed, class:'form-check-label', for:'todo.completed' %>
        <%= todo.description%> </div>
      <p class="card-text"><small class="text-muted">Last updated <%= todo.created_at %></small></p>
      <%= link_to "Show", show_todos_path(todo), class: 'btn btn-info' %>
      <%= link_to "Edit", edit_todo_path(todo), class: 'btn btn-info' %>
      <%= link_to "Complete", complete_todo_path(todo), class: 'btn btn-info' %>
      <%= link_to 'Delete', delete_todo_path(todo), method: :delete, data: { confirm: 'Estas seguro?' }, class: 'btn btn-danger'%>


    </div>
  </div>
<% end %>
</div>
<% end %>

app/views/todos/list.html.erb
<div class="container">
  <div class="row">
    <div class="col">
    <h2>Completed</h2>
      <%@todo_completed.each do |todo|%>
                <tbody>
                <ul>
                    <li><%= todo.description %></li>
                    <li> <%= link_to "Edit", edit_todo_path(todo), class: 'btn btn-info' %> <%= link_to 'Delete', delete_todo_path(todo), class: 'btn btn-danger', method: :delete, data: { confirm: 'Estas seguro?' }%></li>
                </ul>
                </tbody>
            <% end %>
    </div>
    <div class="col">
    <h2>Uncompleted</h2>

      <%@todo_uncompleted.each do |todo|%>
                <tbody>
                <ul>
                    <li><%= todo.description %></li>
                    <li> <%= link_to "Edit", edit_todo_path(todo), class: 'btn btn-info' %> <%= link_to 'Delete', delete_todo_path(todo), class: 'btn btn-danger', method: :delete, data: { confirm: 'Estas seguro?' }%></li>
                </ul>
                </tbody>
            <% end %>
    </div>
  </div>
  </div>

app/views/todos/new.html.erb
<div class='row'>
    <div class="col-md-6 offset-md-3">
        <%= form_with(model: @todo, local: true) do |f| %>
            <div class="form-check">
                <%= f.check_box :completed, class: 'form-check-input' %>
                <%= f.label :completed, class: 'form-check-label', for: 'completed' %>
            </div>
            <div class="form-group">
                <%= f.label :description %>
                <%= f.text_field :description, class: 'form-control' %>
            </div>
            <br>
            
            <%= f.submit class: 'btn btn-info'%>
        <% end %>
    </div>
</div>

app/views/todos/show.html.erb
<div class="card-deck">

  <div class="card">
    <div class="card-body">
    <div class="form-check">
        <%= check_box_tag(:completed, @todo.completed, @todo.completed, disabled: true) %>
        <% label :completed, class:'form-check-label', for:'todo.completed' %>
       <%= @todo.description%> </div>
      <p class="card-text"><small class="text-muted">Last updated <%= @todo.created_at %></small></p>
    </div>
  </div>
</div>

<%= link_to  "<< Back", root_path %>